# Sample configuration for Kafka Self-Healing System
# This demonstrates YAML format with environment variable substitution

cluster:
  cluster_name: "${CLUSTER_NAME:production-kafka}"
  monitoring_interval_seconds: 30
  default_retry_policy:
    max_attempts: 3
    initial_delay_seconds: 30
    backoff_multiplier: 2.0
    max_delay_seconds: 300
  nodes:
    - node_id: "kafka-broker-1"
      node_type: "kafka_broker"
      host: "${KAFKA_BROKER_1_HOST:kafka1.example.com}"
      port: 9092
      jmx_port: 9999
      monitoring_methods: ["jmx", "socket"]
      recovery_actions: ["restart_service", "cleanup_logs"]
      retry_policy:
        max_attempts: 5
        initial_delay_seconds: 60
        backoff_multiplier: 1.5
        max_delay_seconds: 600
    
    - node_id: "kafka-broker-2"
      node_type: "kafka_broker"
      host: "${KAFKA_BROKER_2_HOST:kafka2.example.com}"
      port: 9092
      jmx_port: 9999
      monitoring_methods: ["jmx", "socket"]
      recovery_actions: ["restart_service"]
    
    - node_id: "zookeeper-1"
      node_type: "zookeeper"
      host: "${ZK_HOST_1:zk1.example.com}"
      port: 2181
      monitoring_methods: ["socket", "cli"]
      recovery_actions: ["restart_service", "cleanup_data"]
    
    - node_id: "zookeeper-2"
      node_type: "zookeeper"
      host: "${ZK_HOST_2:zk2.example.com}"
      port: 2181
      monitoring_methods: ["socket", "cli"]
      recovery_actions: ["restart_service"]

notification:
  smtp_host: "${SMTP_HOST:smtp.company.com}"
  smtp_port: 587
  smtp_username: "${SMTP_USERNAME:alerts@company.com}"
  smtp_password: "${SMTP_PASSWORD:secret123}"
  use_tls: true
  use_ssl: false
  sender_email: "${SENDER_EMAIL:kafka-alerts@company.com}"
  recipients:
    - "${ADMIN_EMAIL:admin@company.com}"
    - "${OPS_EMAIL:ops@company.com}"
  subject_prefix: "[Kafka Self-Healing]"